name: "Bug Report"
description: "Report a software bug"
title: "[BUG]: "
labels: ["bug"]

body:
  - type: textarea
    id: bug-content
    attributes:
      label: "Bug Details"
      description: "Replace the text under each heading with your own details."
      value: |
        ### Description
        [A clear and concise description of what the bug is.]

        ### Steps to Reproduce
        1. [Step 1] - Click on..
        2. [Step 2] - Select that part ...
        3. [Step 3] - See error ...

        ### Demo Video/Screenshots
        [Paste Demo video / Screenshots here (if Relevant)]

        ### Expected Behavior
        [A clear and concise description of what you expected to happen.]

        ### Environment
        - **OS:** [e.g. Windows 11]
        - **Browser:** [e.g. Chrome]
        - **Version:** [e.g. 1.0.0]

        ### Additional Context
        [Add any other context]
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "Issue Category"
      description: "Select the tag that best fits this request."
      options:
        - "`GOOD FIRST ISSUE`"
        - "`BUG`"
        - "`DOCUMENTATION`"
        - "`DUPLICATE`"
        - "`ENHANCEMENT`"
        - "`HACKTOBERFEST`"
        - "`HELP WANTED`"
        - "`INVALID`"
        - "`QUESTION`"
        - "`WONTFIX`"
  - type: checkboxes
    id: work
    attributes:
      label: "Contribution"
      options:
        - label: "I am willing to fix this bug."