name: "🚀 Feature Request"
description: Suggest an idea for this project
title: "[BUG] "
labels: ["enhancement"]

body:
  - type: textarea
    id: problem
    attributes:
      label: "Is your feature request related to a problem?"
      description: "Describe the problem you're facing"
      placeholder: "Ex. I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: "What do you want to happen?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "Any alternative solutions?"