name: "🐞 Bug Report"
description: Report a bug to help us improve
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: markdown
    attributes:
      value: "## Device Information"
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g., macOS, Windows, Linux
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g., Chrome, Firefox, Safari
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., 1.0.0
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
  - type: checkboxes
    id: working
    attributes:
      label: Contribution
      options:
        - label: I am willing to work on this issue myself.
  - type: checkboxes
    id: beginner-friendly
    attributes:
      label: Good First Issue
      description: Is this a good starting point for a brand new contributor?
      options:
        - label: I believe this is a beginner-friendly issue.