name: "Feature Request"
description: "Suggest an idea or improvement"
title: "[FEATURE]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: feature-content
    attributes:
      label: "Feature Details"
      value: |
        ### Problem Statement
        [Describe the problem you're facing. Ex. I'm always frustrated when...]

        ### Proposed Solution
        [A clear and concise description of what you want to happen.]

        ### Alternatives Considered
        [A clear and concise description of any alternative solutions or features you've considered.]

        ### Additional Context
        [Add any other context or screenshots about the feature request here.]
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "Issue Category"
      description: "Select the tag that best fits this request."
      options:
        - "`GOOD FIRST ISSUE`"
        - "`BUG`"
        - "`DOCUMENTATION`"
        - "`DUPLICATE`"
        - "`HACKTOBERFEST`"
        - "`HELP WANTED`"
        - "`INVALID`"
        - "`QUESTION`"
        - "`WONTFIX`"
  - type: checkboxes
    id: work
    attributes:
      label: "Contribution"
      options:
        - label: "I am willing to work on this."