name: "🚀 Feature Request"
description: "Suggest an idea or improvement"
title: "[FEATURE]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: feature-content
    attributes:
      label: "Feature Details"
      description: "Replace the text under each heading with your own details."
      value: |
        ### 💡 Problem Statement
        [Describe the problem you're facing here]

        ### 🎯 Proposed Solution
        [What do you want to happen?]

        ### 📎 Additional Context
        [Add screenshots or any other info here]
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "Issue Category"
      description: "Select the tag that best fits this request."
      options:
        - "**[ GOOD FIRST ISSUE ]**"
        - "**[ HELP WANTED ]**"
        - "**[ UI/UX ]**"
        - "**[ PERFORMANCE ]**"
        - "**[ DOCUMENTATION ]**"
    validations:
      required: true

  - type: checkboxes
    id: work
    attributes:
      label: "Contribution"
      options:
        - label: "**I am willing to work on this.**"